# Generated by Django 6.0.5 on 2026-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuse',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('excused', 'Excused')], default='pending', max_length=20),
        ),
    ]
