# Generated by Django 6.0.5 on 2026-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_excuse_confirmation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
