# Generated by Django 6.0.5 on 2026-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_servant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
